
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package comp_proy;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int MASMAS = 45;
  public static final int DOSPUNTOS = 27;
  public static final int MENOSMENOS = 46;
  public static final int POR = 32;
  public static final int IDENTIF = 53;
  public static final int DIFERENTE = 40;
  public static final int CASE = 3;
  public static final int TIPO_STRING = 16;
  public static final int MENOS_UNARIO = 47;
  public static final int MENORIGUAL = 44;
  public static final int NOT = 38;
  public static final int AND = 36;
  public static final int ESIGUAL = 39;
  public static final int IGUAL = 29;
  public static final int OR = 37;
  public static final int DIV = 33;
  public static final int CUAD_C = 25;
  public static final int CUAD_A = 24;
  public static final int MAIN = 7;
  public static final int IF = 6;
  public static final int MAYORIGUAL = 43;
  public static final int EOF = 0;
  public static final int READ_FLOAT = 18;
  public static final int RETURN = 9;
  public static final int COMPLEMENTO = 35;
  public static final int error = 1;
  public static final int COMA = 28;
  public static final int LIT_STRING = 52;
  public static final int TIPO_CHAR = 13;
  public static final int MENOS = 31;
  public static final int MENOR = 42;
  public static final int NULL = 8;
  public static final int LIT_CHAR = 51;
  public static final int LIT_BOOLEANO = 50;
  public static final int BREAK = 2;
  public static final int TIPO_INT = 15;
  public static final int CURS_C = 23;
  public static final int SWITCH = 10;
  public static final int MAYOR = 41;
  public static final int CURS_A = 22;
  public static final int POTENCIA = 34;
  public static final int LIT_FLOTANTE = 49;
  public static final int READ_INT = 17;
  public static final int ELSE = 5;
  public static final int WHILE = 11;
  public static final int DEFAULT = 4;
  public static final int TIPO_FLOAT = 14;
  public static final int TIPO_BOOL = 12;
  public static final int LIT_ENTERO = 48;
  public static final int HASHTAG = 26;
  public static final int PAREN_C = 21;
  public static final int PAREN_A = 20;
  public static final int PRINT = 19;
  public static final int MAS = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BREAK",
  "CASE",
  "DEFAULT",
  "ELSE",
  "IF",
  "MAIN",
  "NULL",
  "RETURN",
  "SWITCH",
  "WHILE",
  "TIPO_BOOL",
  "TIPO_CHAR",
  "TIPO_FLOAT",
  "TIPO_INT",
  "TIPO_STRING",
  "READ_INT",
  "READ_FLOAT",
  "PRINT",
  "PAREN_A",
  "PAREN_C",
  "CURS_A",
  "CURS_C",
  "CUAD_A",
  "CUAD_C",
  "HASHTAG",
  "DOSPUNTOS",
  "COMA",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POTENCIA",
  "COMPLEMENTO",
  "AND",
  "OR",
  "NOT",
  "ESIGUAL",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "MASMAS",
  "MENOSMENOS",
  "MENOS_UNARIO",
  "LIT_ENTERO",
  "LIT_FLOTANTE",
  "LIT_BOOLEANO",
  "LIT_CHAR",
  "LIT_STRING",
  "IDENTIF"
  };
}

